# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false

os:
  edit: "zed {{filename}}"
  editAtLine: "zed {{filename}}:{{line}}"

gui:
  useHunkModeInStagingView: false
  tabWidth: 2
  nerdFontsVersion: "3"

git:
  # Cycle between pagers with `|`
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --width={{columnWidth}}
